- exc/elv_xc.c
- Fix a crash in exc when repeats > 0 and encoder name is not correct
- Fix a bug in exc when extracting only one image
> Fix a crash in exc when encoder name is not correct

- avpipe.go
- avpipe_test.go
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_level.c
- libavpipe/src/avpipe_mux.c
- libavpipe/src/avpipe_xc.c
- Fix audio/video synchronization when doing random access on the muxed file.
> Fix audio/video sync for muxed output

- avpipe.c
- avpipe.go
- avpipe.h
- avpipe_test.go
- elvxc/cmd/probe.go
- elvxc/cmd/transcode.go
- exc/elv_xc.c
- libavpipe/include/avpipe_version.h
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_mux.c
- libavpipe/src/avpipe_xc.c
- live/lhr_tool_test.go
- live/live_probe_test.go
- live/live_source.go
- live/ts_recorder_test.go
- run_live_tests.sh
issue: https://github.com/eluv-io/avpipe/issues/4
- Add connection timeout to avpipe params for RTMP/MPEGTS streams.
- For RTMP listen mode, avpipe will wait for incoming connection up to connection_timeout (if connection_timeout > 0).
- For UDP/MPEGTS, avpipe will wait for incoming UDP datagrams up to connection_timeout (if connection_timeout > 0).
- Modify avpipe_probe to use xcparams.
- Add unit tests for live stream probing (RTMP and MPEGTS)
> Add connection timeout to avpipe params and enhance probe API

- avpipe.c
- avpipe.go
- avpipe_errors.go
- avpipe_test.go
- libavpipe/include/avpipe_xc.h
- live/live_probe_test.go
- This issue is detected in fabric when reading media files from cloud fail (https://github.com/qluvio/content-fabric/issues/2260).
- Fix a double free of memory when reading input files fail.
- Add some unit tests to simulate failing situations in input IO.
> Fix bad io crash

- README.md
- avpipe.c
- avpipe.go
- avpipe_test.go
- libavpipe/include/avpipe_version.h
- libavpipe/src/avpipe_xc.c
- live/lhr.go
- scripts/cmd_samples.sh
- ts/parse_ts/main.go
- utils/src/url_parser.c
- Fix a crash when input file URLs have special characters like ":".
- Fix a bug in transcoding audio join/merge/pan when input sample rate doesn't match with AAC.
- Add more unit tests for audio.
- Fix a bug in setting last_key_frame_pts when setting IDR key frames.
- Let nvidia encoders to set the level (nvidia encoder level doesn't match with h264 level).
- More design documents and updating README file.
> Special url

- avpipe.c
- avpipe_test.go
- exc/elv_xc.c
- libavpipe/Makefile
- libavpipe/include/avpipe_version.h
- libavpipe/src/avpipe_udp_thread.c
- libavpipe/src/avpipe_xc.c
- live/ts_recorder_test.go
- utils/include/elv_sock.h
- utils/src/elv_channel.c
- utils/src/elv_sock.c
- utils/test/Makefile
- utils/test/elv_channel_test.c
issue: https://github.com/eluv-io/avpipe/issues/10
- Fix pts/dts issue when transcoding mpegts using avpipe audio filters.
- Use audio filters in general instead of using resampling library.
- Refactor UDP thread in case of mpegts transcoding.
- Fix a small issue in elv_channel and add unit test for it
- Support incompatible sample rate with AAC in general case and add unit test for it
> Use audio filter

- avpipe_test.go
- libavpipe/include/avpipe_version.h
- libavpipe/src/avpipe_xc.c
This change set:
- Fixes the B frame issue due to clearing pict_type flag and let the B frames to go to encoder properly (only clear pict_type for prores / jpeg2000 decoders).
- Syncs RTMP audio / video if they are out of sync.
- Modifies the unit tests to skip a test if the input file doesn't exist.
> Fix bframes

- Makefile
- avpipe.c
- avpipe.go
- elvxc/cmd/transcode.go
- exc/elv_xc.c
- libavpipe/Makefile
- libavpipe/include/avpipe_utils.h
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_utils.c
- libavpipe/src/avpipe_xc.c
- libavpipe/src/scte35.c
- libavpipe/src/scte35.h
- ts/scte35_test.go
Add support for parsing a SCTE-35 data stream in MPEG-TS, if present.
SCTE-35 signals are aligned with the video stream.
Bonus:
- connect input stats for video and audio first decoded frame / PTS
> SCTE parser for MPEG-TS

- avpipe.c
- avpipe.go
- avpipe_test.go
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_xc.c
- Add new stat event `in_stat_first_keyframe_pts` to signal application when first keyframe available in the input.
- This is necessary to mark the beginning of the stream properly.
- Also modify generation of `first_decoding_audio_pts` and `first_decoding_video_pts` to reflect the first audio/video packet that goes to the decoder.
> Keyframe stats

- avpipe.go
- avpipe_errors.go
This simple change will instruct CGO to not look for `libxcoder` unless a build tag of `netting` is used.  Build tags in `content-fabric` builds will propagate, so the following will work on a `content-fabric` build:
```shell
go install -tags WAPC,avpipe,netint ./...
```
On platforms like the Mac/darwin, where `libxcoder` is not available, a user only needs to build `content-fabric` this way, omitting the tag:
```shell
go install -tags WAPC,avpipe ./...
```
Also, while adding build tags to `avpipe`, I also enabled `RPATH` setting on Linux.  The method for Mac/darwin is a bit more involved and may be moot with an FFmpeg change, but this is known to work on Linux as is.  This will prevent a user from not being able to use `qfab` with `avpipe` without moving libraries a lot.  The `RPATH` …
> Use Go build tags to select `xcoder` as dependency

- avpipe.go
- elvxc/cmd/transcode.go
- exc/elv_xc.c
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_xc.c
issue: https://github.com/eluv-io/avpipe/issues/34
- Add a new parameter `video_frame_duration_ts` to avpipe to set the frame duration of output video stream to a specific number based on ts.
- This feature will help to cut the fmp4 segments properly and exactly at specific timebase. For example, if input stream/video is an RTMP stream with various frame duration, this feature will help to produce proper mezzanines with exactly equal duration.
> Frame duration

- libavpipe/include/avpipe_utils.h
- libavpipe/src/avpipe_utils.c
- libavpipe/src/avpipe_xc.c
The problem to solve is that when transcoding from RTMP (FLV) to H264, the resulting bitrate varies widely with the timebase setting.  This is a quirk of the transcoder that only manifests for the FLV-MP4/H264 use case.  I reproduced this problem exactly as described with ffmpeg sample `transcoding.c`
For example - RTMP timebase is 1000:
- if we set video timebase to a small number (like 30 or 60) the resulting bitrate is larger than desired - for example 14 Mbps when rate is set to 5Mbps
- if we set video timebase to a large number like 15360 or 16000 the resulting bitrate is 700 Kbps when set to 5 Mbps (and also when set to 10 Mbps)
- if we set video timebase to any number around 1000 (like 960!) the resulting bitrate is correct - 5Mbps when set to 5Mbps
The main functional change is …
> Change video timebase setting to allow controlling bitrate

- elvxc/cmd/transcode.go
- libavpipe/include/avpipe_utils.h
- libavpipe/include/avpipe_version.h
- libavpipe/src/avpipe_utils.c
- libavpipe/src/avpipe_xc.c
- utils/src/elv_channel.c
- Don't shift pts for audio join/merge/pan (regression).
- Add stream index when dumping frame.
- If a channel has closed don't send a message.
> Don't shift pts for audio join/merge/pan

- libavpipe/src/avpipe_xc.c
After building avpipe and ffmpeg with debug symbols and running under tcMalloc I found the leak to be originating from the format context on probe.  After trying lots of stuff this made the tcMalloc leak go away.  On the order of 2.5MB for BBB in 4K per probe.  Hoping Reza can see if this is dangerous although I stepped through using the debugger too so the code does not blow up on TestMezMaker.  After further consideration we may want to set the buffer to NULL after free?
> leaking pb->buffer

- live/lhr.go
Simple fix, just avoids calling `Close` on a nil content, which panics.
> Fix nil error on failure to get manifest

- libavpipe/src/avpipe_xc.c
According to ffmpeg documentation, the user should only free this themself if the io context was set by the user manually. Resolves crash caused by #41. 
This caused a crash on probing an SRT or RTMP stream. I also slightly cleaned up the manual checks on protocols to use FFMPEG's own flag for custom IO.
Quote from FFMPEG documentation about `pb`:
```C
/**
* I/O context.
*
* - demuxing: either set by the user before avformat_open_input() (then
*             the user must close it manually) or set by avformat_open_input().
* - muxing: set by the user before avformat_write_header(). The caller must
*           take care of closing / freeing the IO context.
*
* Do NOT set this field if AVFMT_NOFILE flag is set in
* iformat/oformat.flags. In such a case, the (de)muxer will handle
* I/O in …
```
> Fix double-free on probe of non-udp stream

- .gitignore
- avpipe.c
- avpipe_test.go
- exc/elv_xc.c
- libavpipe/include/avpipe_version.h
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_xc.c
- live/rtmp_recorder_test.go
- live/srt_recorder_test.go
- utils/src/elv_sock.c
- This will keep the API and modifies the implementation under the hood.
- Move blocking code from avpipe_init() into avpipe_xc(). This will allow to obtain the handle for cancellation.
- Add some unit tests for the hanging cases with SRT and RTMP.
Nate will continue to enhance corner cases and memory cleanup.
> Make avpipe_init() nonblocking

- avpipe.go
Change `StreamInfo.SideData` to `StreamInfo.SideDataList`, change type to generic `[]interface{}`
Add `Type` field to `SideDataDisplayMatrix` with JSON fieldname "side_data_type" to match ffprobe output format. (value should always set to string "Display Matrix") Only return a `SideDataDisplayMatrix` element within `StreamInfo.SideDataList` if there is a non-zero rotation found. 
Minor edit to get rid of compiler warning "Redundant '_' expression"
> SideData changes to more closely match ffprobe JSON and media_struct.MediaStruct

- avpipe.go
- elvxc/cmd/probe.go
This fixes and completes the changes in side data in the previous commit.
Here is the compile error with previous change set:
```
e.go $WORK/b085/_cgo_gotypes.go $WORK/b085/mux.cgo1.go $WORK/b085/_cgo_import.go
cmd/probe.go:101:11: info.SideData undefined (type avpipe.StreamInfo has no field or method SideData)
cmd/probe.go:104:44: info.SideData undefined (type avpipe.StreamInfo has no field or method SideData)
cmd/probe.go:105:47: info.SideData undefined (type avpipe.StreamInfo has no field or method SideData)
```
> fix-side-data

- libavpipe/examples/decoding_encoding.c
- libavpipe/examples/transcode_aac.c
- libavpipe/examples/transcoding.c
- libavpipe/src/avpipe_xc.c
Remove use of deprecated `av_init_packet`. 
I also updated the examples, but the real codepath is only in `avpipe_xc.c`. `av_packet_alloc` initializes all fields to default, and `av_packet_unref` will also reset fields to default. 
Went over this in detail with Serban, so it should be safe.
> Address deprecation warning

- avpipe.go
- avpipe_test.go
- elvxc/cmd/transcode.go
- live/lhr_tool_test.go
- live/rtmp_recorder_test.go
- live/ts_recorder_test.go
The go side of the audio index is a little awkward because of the audio index array always taking up the full amount of audios, which makes the marshalled transcode parameters harder to read. Additionally, there can be a mismatch between the number of audios and the number of assigned audio indices, which this PR removes.
This is largely a nonfunctional PR, as everything should really remain the same. The C side should be identical.
It corresponds to another PR of the same branch name on content-fabric.
> Clean up audio index

- avpipe.go
- avpipe_test.go
- elvxc/cmd/transcode.go
- exc/elv_xc.c
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_level.c
- libavpipe/src/avpipe_xc.c
issue: https://github.com/eluv-io/avpipe/issues/61
- Add new fields profile/level to xc params
- Enforce profile/level if they exist in the xc params
- Add a unit test for setting profile/level
> Set profile/level if exist in the parameters

- avpipe.c
- libavpipe/src/avpipe_xc.c
The comment describes how this happens pretty well. This change, and the error that it returns being recoverable together result in the removal of `eav_filter_init` from the list of recoverable errors.
I'm open to suggestions on which type of error, but I think either `eav_read_input` or `eav_open_input` are the correct ones. It's hard to say.
> Detect missing codec parameters

- README.md
- avpipe.c
- avpipe.go
- elvxc/cmd/mux.go
- exc/elv_mux.c
- exc/elv_xc.c
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_mux.c
- libavpipe/src/avpipe_xc.c
- live/lhr_buffer.go
- live/ts_recorder_test.go
- scripts/sample_mux_spec_abr15.txt
Solves issues: https://github.com/eluv-io/avpipe/issues/67, https://github.com/eluv-io/avpipe/issues/68
- Increase muxing capacity up to 4*4096 ABR segments (more than 8 hours).
- Add capability to mux to MP4 in addition to fMP4. This can be chosen using the format in transcoding parameters.
- During muxing adjust output PTS/DTS and start from zero.
- Better EOF detection when muxing multiple streams.
- Start muxing after the first keyframe detection.
- Some enhancements and fixes in mux output seeker interface.
- Fix a memory leak in avpipe mux when muxing is filished
> Mux modification

- .gitignore
- README.md
- avpipe.c
- avpipe.go
- avpipe_test.go
- elvxc/cmd/transcode.go
- init-local.sh
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_io.c
- libavpipe/src/avpipe_xc.c
- live/lhr_tool_test.go
This PR consists of a couple of things that are pretty well separated into commits:
- Add `start_file` and `end_file` as stat events.
- Format the README and add a mention of `exc` and `elvxc`.
- Remove redundant `out_tracker_t` allocations.
- Add assorted helper methods to go enums.
- Simplify test logging
There will be an associated PR in qfab to actually make these stats visible.
> Assorted Improvements, Stats

- avpipe.c
- avpipe.go
- avpipe_log.go
- go.mod
- go.sum
- libavpipe/src/avpipe_xc.c
This PR is an approach that I'm pretty happy with that will make logs much more parseable. As best as I can tell by manual inspection, every log that is emitted from `avpipe` will now include the `av_handle` as a parseable element of the log.
For LRO-styled jobs that use the v2 `XcInit` -> `XcRun` flow, this matches with the existing handle in the transcode context. For single-shot jobs that use `Xc` or `Mux`, this positive 32-bit int handle is generated at the start of these `c` functions after the `xctx_t` is created. This also includes the threads that are created, except for the UDP in thread, as it wasn't trivial to include the handle in that location.
This is implemented by using a `sync.Map` as a form of goroutine(thread)-local storage, and inserting that information if it is known …
> Include xc handle in logs

- avpipe.go
- avpipe_log.go
- avpipe_log_test.go
- go.mod
- go.sum
This is an accompaniment to the content-fabric [PR](https://github.com/qluvio/content-fabric/pull/3176).
The primary thing this PR does is add some more utility to the `AVType` type, as well as intercept error and warn logs and send them to a channel. In order to reduce blocking, this just skips that if the channel is free.
> Intercept WARN/ERROR logs

- avpipe.go
- elvxc/cmd/transcode.go
This is all that's necessary for `elvxc` to work correctly.
Also, I realized that on my computer, `elvxc` has a busted signature whenever I build it for whatever reason. Took a while to debug. Genuinely no idea what is really going on with that.
```
[nate-copy-ts-piping][~/eluvio/avpipe/elvxc]$ go install ./...
[nate-copy-ts-piping][~/eluvio/avpipe/elvxc]$ which elvxc
/Users/narmstrong/go/bin/elvxc
[nate-copy-ts-piping][~/eluvio/avpipe/elvxc]$ ls -l ~/go/bin/elvxc
-rwxr-xr-x  1 narmstrong  staff  8129192 Mar 11 19:56 /Users/narmstrong/go/bin/elvxc
[nate-copy-ts-piping][~/eluvio/avpipe/elvxc]$ codesign -vv elvxc
elvxc: invalid signature (code or signature have been modified)
In architecture: arm64
[nate-copy-ts-piping][~/eluvio/avpipe/elvxc]$ elvxc
[1]    60950 killed     elvxc …
```
> Minimum required to function like exc

- libavpipe/src/avpipe_format.c
Fix accidental removal of 'udp://' (mpegts) during PR cleanup.
> fix mpegts live

- doc/dev.md
- libavpipe/src/avpipe_copy_mpegts.c
```
./bin/exc -f udp://127.0.0.1:9000 -xc-type all -format fmp4-segment -video-bitrate 9500000 -audio-bitrate 192000 -sample-rate 48000  -video-seg-duration-ts 2700000  -audio-seg-duration-ts 1428480   -force-keyint 100  -copy-mpegts 0 -enc-height 1080 -enc-width 1920 -sync-audio-to-stream-id 512   -audio-index 1,2  -copy-mpegts 1`
```
Using `tstools` to check output parts:
- for mac: `git@github.com:sepkooo/tstools-for-macos`
- for linux: `https://github.com/kynesim/tstools`
Print the continuity counts for a file - first and last:
```
tsreport -cnt 0100 ts-segment-00003.ts  | grep CC
```
Each file starts with 0:
```
tsreport -cnt 1 ts-segment-00001.ts  | grep CC
CC: first: 0, last: 14; duplicate packets: 0
CC: first: 5, last: 4; duplicate packets: 0
CC: first: 10, last: 9; duplicate …
```
> Preserve continuity counts in MPEGTS output

- exc/elv_xc.c
- libavpipe/src/avpipe_xc.c
- rules.make
This resolves some (hopefully all) differences in SPS/PPS between mezzanine and ABR encodings (`fmp4-segment` and `dash` formats respectively).
No differences in SPS/PPS observed in simple test using exc.
Note that our ABR segments don't seem to have b-frames even without setting `max_b_frames` to 0. Maybe this is due to another encoder setting related to frame buffers or something.
A future improvement, as noted in the TODO comment, is to add a parameter for b-frames to the API.
Also removed xcoder when building on Mac.
Issues:
- https://github.com/eluv-io/avpipe/issues/95
- https://github.com/qluvio/content-fabric/issues/3007
- https://github.com/qluvio/content-fabric/issues/3274
- https://github.com/qluvio/archive-avpipe/issues/292
> Disable b-frames for ABR encoding

- libavpipe/include/avpipe_utils.h
- libavpipe/src/avpipe_utils.c
- libavpipe/src/avpipe_xc.c
1. Set probe result start time to 0 if not explicitly specified by the format
This is to avoid returning AV_NOPTS_VALUE since that is an internal constant in ffmpeg and there is no differentiation needed between start time not specified and start time 0 (they are treated the same way).
2. Estimate stream duration if not specified by the format
This is an enhancement for support of matroska/webm files with no duration.  There is an optional duration tag - use it if found.
Future note: we could also determine duration by reading a few starting frames, then seeking to the end and read the last frames.
Example probe result (elvxc):
```
Stream[0]
stream_id: 0
codec_type: video
codec_id: 167
codec_name: vp9
profile: Profile 0
level: -99
duration_ts: 9923600
time_base: 1/1000
nb_frames: 0 …
```
> Probe use duration tag if not provided by format

- avpipe.go
- avpipe_test.go
- elvxc/cmd/mux.go
- elvxc/cmd/probe.go
- elvxc/cmd/transcode.go
- goavpipe/goavpipe.go
- goavpipe/structs.go
- live/lhr.go
- live/lhr_tool_test.go
- live/live_probe_test.go
- live/rtmp_recorder_test.go
- live/srt_recorder_test.go
- live/ts_recorder_test.go
This PR moves some structs from the main `avpipe` package into a smaller package called `goavpipe`, which allows `legacy_imf_dash_extract` to depend on it without needing a C toolchain.
I will make an associated PR in content-fabric to update dependencies as well.
> Move XcParams,structs to new package

- exc/elv_xc.c
Fixes crash in avpipe exc.
We should make ownership semantics a bit more explicit.
> Set opaque null after free in exc

- libavpipe/src/avpipe_format.c
- libavpipe/src/avpipe_utils.c
- libavpipe/src/avpipe_xc.c
The main problem was that the audio PTS/DTS was not scaled from the original timebase of 1/1000 to the target timebase of 1/48000.
webm/matroska containers use timebase 1/1000 for both audio and video and use opus codec for audio predominantly.
The code to rescale was in place but it was conditioned on the input codec being the same as the output codec which is not correct (in the case input codec is opus and output is AAC).
I have also researched the situation with audio frames having nagative PTS and preambles.  I documented it in this ticket: https://github.com/eluv-io/avpipe/issues/105
> Fix opus audio codec

- doc/dev.md
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_filters.c
- libavpipe/src/avpipe_format.c
- libavpipe/src/avpipe_format.h
- libavpipe/src/avpipe_xc.c
Fix audio rescale in the main transcoding flow.
The general idea is to rescale the decoded audio frame before sending to the filter (and then to the encoder).
Initialize the audio buffer source filter using the desired encoder timebase, such that the filter expects the frames to be in the encoder timebase and process correctly.
No longer rescale audio packets before sending them to the packager, because they are now returned by the encoder in the correct timescale of the encoder.
I left the video transcoding flow unchanged and will come back with a separate PR for video.
> Fix audio rescale flow - rescale before filter

- avpipe.c
- exc/elv_mux.c
- goavpipe/structs.go
- libavpipe/include/avpipe_xc.h
- libavpipe/src/avpipe_mux.c
- libavpipe/src/avpipe_xc.c
This partially resolves https://github.com/qluvio/content-fabric/issues/3266.
The main description here is copied from that issue.
Additionally, there are a few miscellaneous changes:
- renaming `last_foo_index` to `foo_count`, because the naming was confusing to me
- assigning muxing inctx params, because previously debug frame level was broken on them
This is intentionally as light as reasonable, and will be followed by the subsequent changes described in the issue (and that I discussed with Serban).
The first iteration is already largely completed.
The first thing to fix the glaring issues with this is to adjust the way that PTS/DTS are adjusted for incoming packets. The simple way to do this has two steps:
1. Estimate the frame duration in the incoming streams, `d_i`.
2. Stamp the …
> Stamp PTS/DTS on muxed packets

- libavpipe/src/avpipe_xc.c
The previous image overlay filter requires images be sized to the target resolution which makes the result slightly inconsistent (may jump when player switches resolution) and the resulting quality is not great.
The correct processing is to apply the overlay to the source video and scale the result.  This way we don't require the image be scaled by the caller (e.g using a Go library in content fabric).
> BREAKING CHANGE - caller code has to adapt to ensure the image is sized for the source video.
> Fix image overlay video filters - apply overlay before scaling

- avpipe.c
- libavpipe/src/avpipe_copy_mpegts.c
- libavpipe/src/avpipe_xc.c
- utils/src/elv_channel.c
Several fixes:
1. Keep demuxing loop robust to minor network errors or corruptions - continue reading and only exit after 300 tries
- low risk since we exit after 300 tries
- I chose 300 to be approx 5 sec at 60fps
2. Fix calculated_frame_duration
- I now have both a decoder and encoder frame duration since they are not the same when we change timebase/timescale and frame durations
- Honor param video_frame_duration_ts - when set, the 'calculated_frame_duration' needs to be set to that
3. For mpegts parts, use the source timebase and calculations (since we are not changing timebase or frame durations in TS output) 
- prior logic was copied from video encoder prep and used the encoder values
4. Additional logging
Here are some examples of infrequent IO errors that cause the decoding loop …
> Handle unreadable or corrupt muxer input
